### PR TITLE
Update client.rb

### PR DESCRIPTION
**Pull request by tennisshoe**
Hi Mark, I made some minor modifications to the search method so we can specify the category etc.

### CODE REVIEW

**Comment by benrugg** [comment]
Hey @tennisshoe - this looks great. Thanks for adding this. Would you mind adding a test or two for this new functionality before we pull it in? 

You can find the other tests for the search functionality in spec/support/shared_examples.rb

**Comment by benrugg** [comment]
Hey @tennisshoe - have you had a chance to add a couple tests for your new kickscraper code? I'd love to pull it in if you have a second to do that!

**Comment by tennisshoe** [comment]
No sorry. I'm actually more of a C / C++ developer... I need to figure out Ruby's unit testing syntax. Will try to find time to work on it this weekend.

**Comment by benrugg** [comment]
Gotcha. Yeah, hopefully you can start with the template of any of the tests that are in there and just go from there. Thanks for working on it.

**Comment by tennisshoe** [comment]
Hi Ben, do you know what version of rspec (and other libraries) should be used to run the test code? I'm struggling to get rspec spec to run properly with just the code off the main brain (none of my modifications)

**Comment by benrugg** [comment]
I'm using 2.14 (mostly because I just haven't updated much in this code since the end of 2013). 

Make sure to do a couple things... 1. Pull the latest version of kickscraper (things with Kickstarter's API changed this week and broke the older version). 2. Put a real user/pass in spec/test_credentials.rb.

Hopefully it'll be easy from there...

**Comment by tennisshoe** [comment]
Ok should be done now. Is there some way to force the code to bind to the 2.14 version of rspec? The code doesn't work on newer versions.

**Comment by benrugg** [comment]
Looking good. Yeah, there is a way to specify versions. I'll merge your code in and then do that. 

Also, make sure you pull in the latest changes from this master repo. Otherwise your code will be out of date.

Thanks for contributing!

**Pull request merged**
